Conan 2

diff --git a/.github/actions/dependencies/action.yml b/.github/actions/dependencies/action.yml
--- a/.github/actions/dependencies/action.yml
+++ b/.github/actions/dependencies/action.yml
@@ -1,22 +1,22 @@
 name: dependencies
 inputs:
+  compiler:
+    required: true
+  compiler_version:
+    required: true
   configuration:
     required: true
 # An implicit input is the environment variable `build_dir`.
 runs:
   using: composite
   steps:
-    - name: unlock Conan
-      shell: bash
-      run: conan remove --locks
     - name: export custom recipes
       shell: bash
       run: |
-        conan config set general.revisions_enabled=1
-        conan export external/snappy snappy/1.1.10@
-        conan export external/rocksdb rocksdb/9.7.3@
-        conan export external/soci soci/4.0.3@
-        conan export external/nudb nudb/2.0.8@
+        conan export --version 1.1.10 external/snappy
+        conan export --version 9.7.3 external/rocksdb
+        conan export --version 4.0.3 external/soci
+        conan export --version 2.0.8 external/nudb
     - name: add Ripple Conan remote
       shell: bash
       run: |
@@ -24,7 +24,7 @@ runs:
         conan remote remove ripple || true
         # Do not quote the URL. An empty string will be accepted (with
         # a non-fatal warning), but a missing argument will not.
-        conan remote add ripple ${{ env.CONAN_URL }} --insert 0
+        conan remote add ripple --index 0 ${{ env.CONAN_URL }}
     - name: try to authenticate to Ripple Conan remote
       id: remote
       shell: bash
@@ -34,24 +34,60 @@ runs:
         # https://docs.conan.io/1/reference/commands/misc/user.html#using-environment-variables
         # https://docs.conan.io/1/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
         # https://docs.conan.io/1/reference/env_vars.html#conan-password-conan-password-remote-name
-        echo outcome=$(conan user --remote ripple --password >&2 \
-          && echo success || echo failure) | tee ${GITHUB_OUTPUT}
+        ## Don't try this yet...
+        # echo outcome=$(conan user --remote ripple --password >&2 \
+        #   && echo success || echo failure) | tee ${GITHUB_OUTPUT}
     - name: list missing binaries
       id: binaries
       shell: bash
       # Print the list of dependencies that would need to be built locally.
       # A non-empty list means we have "failed" to cache binaries remotely.
       run: |
-        echo missing=$(conan info . --build missing --settings build_type=${{ inputs.configuration }} --json 2>/dev/null  | grep '^\[') | tee ${GITHUB_OUTPUT}
+        # echo missing=$(conan info . --build missing --settings build_type=${{ inputs.configuration }} --json 2>/dev/null  | grep '^\[') | tee ${GITHUB_OUTPUT}
     - name: install dependencies
+      env:
+        BUILD_TYPE: ${{ inputs.configuration }}
       shell: bash
       run: |
-        mkdir ${build_dir}
-        cd ${build_dir}
-        conan install \
-          --output-folder . \
-          --build missing \
-          --options tests=True \
-          --options xrpld=True \
-          --settings build_type=${{ inputs.configuration }} \
-          ..
+        set -x
+        echo $PWD
+
+        python3 <<EOF
+        import shutil
+        import subprocess
+        import sys
+        from multiprocessing import cpu_count
+        from pathlib import Path
+
+        conanhome = Path(subprocess.check_output(["conan", "config", "home"], text=True).strip())
+        conan_profile_path = conanhome / "profiles" / "default"
+        global_conf = conanhome / "global.conf"
+        default_profile = Path.cwd() / "conan_profile" / "default"
+        profile_cmd = ["conan", "profile", "show", "--profile:all", "default"]
+        global_defaults = f"""
+        tools.build:verbosity = verbose
+        tools.build:jobs = {(n:=cpu_count())}
+        core.download:parallel = {n}
+        core.upload:parallel = {n}
+        """
+
+        if conan_profile_path.is_file():
+            print(f"conan default profile {conan_profile_path} already exists!")
+        else:
+            conan_profile_path.parent.mkdir(parents=True, exist_ok=True)
+            shutil.copy(default_profile, conan_profile_path)
+            print(f"Copied {default_profile.resolve()} to {conan_profile_path.resolve()}")
+
+        subprocess.run(profile_cmd)
+
+        if "tools.build:verbosity" not in global_conf.read_text(encoding="utf-8"):
+            with global_conf.open("a", encoding="utf-8") as f: f.write(global_defaults)
+        EOF
+
+        conan install . \
+          --output-folder "${build_dir}" \
+          --settings build_type="${BUILD_TYPE}" \
+          --build missing
+
+        # conan install . --output-folder "build" --settings build_type="Release" --build missing
+        # conan install . --output-folder "build" --settings build_type="Debug" --build missing
