just try nix

diff --git a/.github/workflows/nix.yml b/.github/workflows/nix.yml
--- a/.github/workflows/nix.yml
+++ b/.github/workflows/nix.yml
@@ -112,7 +112,6 @@ jobs:
           - compiler: clang
             compiler_version: 14
         cmake-args:
-          -
           - "-Dunity=ON"
     needs: dependencies
     runs-on: [self-hosted, heavy]
@@ -145,206 +144,219 @@ jobs:
           compiler: ${{ matrix.compiler }}
           compiler_version: ${{ matrix.compiler_version }}
       - name: build
-        uses: ./.github/actions/build
-        with:
-          generator: Ninja
-          configuration: ${{ matrix.configuration }}
-          compiler: ${{ matrix.compiler }}
-          compiler_version: ${{ matrix.compiler_version }}
-          cmake-args: "-Dassert=TRUE -Dwerr=TRUE ${{ matrix.cmake-args }}"
+        env:
+          BUILD_TYPE: ${{ matrix.configuration }}
+          COMPILER: ${{ matrix.compiler }}
+          COMPILER_VERSION: ${{ matrix.compiler_version }}
+        run: |
+          mkdir build && cd build &&
+          if [ -n ${{ matrix.cmake-args }} ]; then
+            echo "Additional cmake-args: ${{ matrix.cmake-args }}"
+          fi
+          conan build .. \
+            --options '&:xrpld=True' \
+            --options '&:test=True'
+        # uses: ./.github/actions/build
+        # with:
+        #   generator: Ninja
+        #   configuration: ${{ matrix.configuration }}
+        #   compiler: ${{ matrix.compiler }}
+        #   compiler_version: ${{ matrix.compiler_version }}
+        #   cmake-args: "-Dassert=TRUE -Dwerr=TRUE ${{ matrix.cmake-args }}"
       - name: test
         run: |
-          ${build_dir}/rippled --unittest --unittest-jobs $(nproc)
+          rippled=$(find . -name "rippled" -type f)
+          ${rippled} --unittest --unittest-jobs $(nproc)
 
-  reference-fee-test:
-    strategy:
-      fail-fast: false
-      matrix:
-        platform:
-          - linux
-        compiler:
-          - gcc
-        configuration:
-          - Debug
-        cmake-args:
-          - "-DUNIT_TEST_REFERENCE_FEE=200"
-          - "-DUNIT_TEST_REFERENCE_FEE=1000"
-    needs: dependencies
-    runs-on: [self-hosted, heavy]
-    container: ghcr.io/legleux/rippled-build-ubuntu:conan2
-    env:
-      build_dir: .build
-    steps:
-      - name: upgrade conan
-        run: |
-          pip install --upgrade "conan<2"
-      - name: download cache
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.configuration }}
-      - name: extract cache
-        run: |
-          mkdir -p ~/.conan
-          tar -xzf conan.tar -C ~/.conan
-      - name: check environment
-        run: |
-          env | sort
-          echo ${PATH} | tr ':' '\n'
-          conan --version
-          cmake --version
-      - name: checkout
-        uses: actions/checkout@v4
-      - name: dependencies
-        uses: ./.github/actions/dependencies
-        env:
-          CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
-        with:
-          configuration: ${{ matrix.configuration }}
-      - name: build
-        uses: ./.github/actions/build
-        with:
-          generator: Ninja
-          configuration: ${{ matrix.configuration }}
-          cmake-args: "-Dassert=TRUE -Dwerr=TRUE ${{ matrix.cmake-args }}"
-      - name: test
-        run: |
-          ${build_dir}/rippled --unittest --unittest-jobs $(nproc)
+  # reference-fee-test:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - linux
+  #       compiler:
+  #         - gcc
+  #       configuration:
+  #         - Debug
+  #       cmake-args:
+  #         - "-DUNIT_TEST_REFERENCE_FEE=200"
+  #         - "-DUNIT_TEST_REFERENCE_FEE=1000"
+  #   needs: dependencies
+  #   runs-on: [self-hosted, heavy]
+  #   container: ghcr.io/legleux/rippled-build-ubuntu:conan2
+  #   env:
+  #     build_dir: .build
+  #   steps:
+  #     - name: upgrade conan
+  #       run: |
+  #         pip install --upgrade "conan<2"
+  #     - name: download cache
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: ${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.configuration }}
+  #     - name: extract cache
+  #       run: |
+  #         mkdir -p ~/.conan
+  #         tar -xzf conan.tar -C ~/.conan
+  #     - name: check environment
+  #       run: |
+  #         env | sort
+  #         echo ${PATH} | tr ':' '\n'
+  #         conan --version
+  #         cmake --version
+  #     - name: checkout
+  #       uses: actions/checkout@v4
+  #     - name: dependencies
+  #       uses: ./.github/actions/dependencies
+  #       env:
+  #         CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
+  #       with:
+  #         configuration: ${{ matrix.configuration }}
+  #     - name: build
+  #       uses: ./.github/actions/build
+  #       with:
+  #         generator: Ninja
+  #         configuration: ${{ matrix.configuration }}
+  #         cmake-args: "-Dassert=TRUE -Dwerr=TRUE ${{ matrix.cmake-args }}"
+  #     - name: test
+  #       run: |
+  #         ${build_dir}/rippled --unittest --unittest-jobs $(nproc)
 
-  coverage:
-    strategy:
-      fail-fast: false
-      matrix:
-        platform:
-          - linux
-        compiler:
-          - gcc
-        configuration:
-          - Debug
-    needs: dependencies
-    runs-on: [self-hosted, heavy]
-    container: ghcr.io/legleux/rippled-build-ubuntu:conan2
-    env:
-      build_dir: .build
-    steps:
-      - name: upgrade conan
-        run: |
-          pip install --upgrade "conan<2"
-      - name: download cache
-        uses: actions/download-artifact@v4
-        with:
-          name: ${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.configuration }}
-      - name: extract cache
-        run: |
-          mkdir -p ~/.conan
-          tar -xzf conan.tar -C ~/.conan
-      - name: install gcovr
-        run: pip install "gcovr>=7,<8"
-      - name: check environment
-        run: |
-          echo ${PATH} | tr ':' '\n'
-          conan --version
-          cmake --version
-          gcovr --version
-          env | sort
-          ls ~/.conan
-      - name: checkout
-        uses: actions/checkout@v4
-      - name: dependencies
-        uses: ./.github/actions/dependencies
-        env:
-          CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
-        with:
-          configuration: ${{ matrix.configuration }}
-      - name: build
-        uses: ./.github/actions/build
-        with:
-          generator: Ninja
-          configuration: ${{ matrix.configuration }}
-          cmake-args: >-
-            -Dassert=TRUE
-            -Dwerr=TRUE
-            -Dcoverage=ON
-            -Dcoverage_format=xml
-            -DCODE_COVERAGE_VERBOSE=ON
-            -DCMAKE_CXX_FLAGS="-O0"
-            -DCMAKE_C_FLAGS="-O0"
-          cmake-target: coverage
-      - name: move coverage report
-        shell: bash
-        run: |
-          mv "${build_dir}/coverage.xml" ./
-      - name: archive coverage report
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage.xml
-          path: coverage.xml
-          retention-days: 30
-      - name: upload coverage report
-        uses: wandalen/wretry.action@v1.4.10
-        with:
-          action: codecov/codecov-action@v4.5.0
-          with: |
-            files: coverage.xml
-            fail_ci_if_error: true
-            disable_search: true
-            verbose: true
-            plugin: noop
-            token: ${{ secrets.CODECOV_TOKEN }}
-          attempt_limit: 5
-          attempt_delay: 210000 # in milliseconds
+  # coverage:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       platform:
+  #         - linux
+  #       compiler:
+  #         - gcc
+  #       configuration:
+  #         - Debug
+  #   needs: dependencies
+  #   runs-on: [self-hosted, heavy]
+  #   container: ghcr.io/legleux/rippled-build-ubuntu:conan2
+  #   env:
+  #     build_dir: .build
+  #   steps:
+  #     - name: upgrade conan
+  #       run: |
+  #         pip install --upgrade "conan<2"
+  #     - name: download cache
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: ${{ matrix.platform }}-${{ matrix.compiler }}-${{ matrix.configuration }}
+  #     - name: extract cache
+  #       run: |
+  #         mkdir -p ~/.conan
+  #         tar -xzf conan.tar -C ~/.conan
+  #     - name: install gcovr
+  #       run: pip install "gcovr>=7,<8"
+  #     - name: check environment
+  #       run: |
+  #         echo ${PATH} | tr ':' '\n'
+  #         conan --version
+  #         cmake --version
+  #         gcovr --version
+  #         env | sort
+  #         ls ~/.conan
+  #     - name: checkout
+  #       uses: actions/checkout@v4
+  #     - name: dependencies
+  #       uses: ./.github/actions/dependencies
+  #       env:
+  #         CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
+  #       with:
+  #         configuration: ${{ matrix.configuration }}
+  #     - name: build
+  #       uses: ./.github/actions/build
+  #       with:
+  #         generator: Ninja
+  #         configuration: ${{ matrix.configuration }}
+  #         cmake-args: >-
+  #           -Dassert=TRUE
+  #           -Dwerr=TRUE
+  #           -Dcoverage=ON
+  #           -Dcoverage_format=xml
+  #           -DCODE_COVERAGE_VERBOSE=ON
+  #           -DCMAKE_CXX_FLAGS="-O0"
+  #           -DCMAKE_C_FLAGS="-O0"
+  #         cmake-target: coverage
+  #     - name: move coverage report
+  #       shell: bash
+  #       run: |
+  #         mv "${build_dir}/coverage.xml" ./
+  #     - name: archive coverage report
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: coverage.xml
+  #         path: coverage.xml
+  #         retention-days: 30
+  #     - name: upload coverage report
+  #       uses: wandalen/wretry.action@v1.4.10
+  #       with:
+  #         action: codecov/codecov-action@v4.5.0
+  #         with: |
+  #           files: coverage.xml
+  #           fail_ci_if_error: true
+  #           disable_search: true
+  #           verbose: true
+  #           plugin: noop
+  #           token: ${{ secrets.CODECOV_TOKEN }}
+  #         attempt_limit: 5
+  #         attempt_delay: 210000 # in milliseconds
 
-  conan:
-    needs: dependencies
-    runs-on: [self-hosted, heavy]
-    container: ghcr.io/legleux/rippled-build-ubuntu:conan2
-    env:
-      build_dir: .build
-      configuration: Release
-    steps:
-      - name: upgrade conan
-        run: |
-          pip install --upgrade "conan<2"
-      - name: download cache
-        uses: actions/download-artifact@v4
-        with:
-          name: linux-gcc-${{ env.configuration }}
-      - name: extract cache
-        run: |
-          mkdir -p ~/.conan
-          tar -xzf conan.tar -C ~/.conan
-      - name: check environment
-        run: |
-          env | sort
-          echo ${PATH} | tr ':' '\n'
-          conan --version
-          cmake --version
-      - name: checkout
-        uses: actions/checkout@v4
-      - name: dependencies
-        uses: ./.github/actions/dependencies
-        env:
-          CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
-        with:
-          configuration: ${{ env.configuration }}
-      - name: export
-        run: |
-          version=$(conan inspect --raw version .)
-          reference="xrpl/${version}@local/test"
-          conan remove -f ${reference} || true
-          conan export . local/test
-          echo "reference=${reference}" >> "${GITHUB_ENV}"
-      - name: build
-        run: |
-          cd tests/conan
-          mkdir ${build_dir}
-          cd ${build_dir}
-          conan install .. --output-folder . \
-            --require-override ${reference} --build missing
-          cmake .. \
-            -DCMAKE_TOOLCHAIN_FILE:FILEPATH=./build/${configuration}/generators/conan_toolchain.cmake \
-            -DCMAKE_BUILD_TYPE=${configuration}
-          cmake --build .
-          ./example | grep '^[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+'
+  # conan:
+  #   needs: dependencies
+  #   runs-on: [self-hosted, heavy]
+  #   container: ghcr.io/legleux/rippled-build-ubuntu:conan2
+  #   env:
+  #     build_dir: .build
+  #     configuration: Release
+  #   steps:
+  #     - name: upgrade conan
+  #       run: |
+  #         pip install --upgrade "conan<2"
+  #     - name: download cache
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: linux-gcc-${{ env.configuration }}
+  #     - name: extract cache
+  #       run: |
+  #         mkdir -p ~/.conan
+  #         tar -xzf conan.tar -C ~/.conan
+  #     - name: check environment
+  #       run: |
+  #         env | sort
+  #         echo ${PATH} | tr ':' '\n'
+  #         conan --version
+  #         cmake --version
+  #     - name: checkout
+  #       uses: actions/checkout@v4
+  #     - name: dependencies
+  #       uses: ./.github/actions/dependencies
+  #       env:
+  #         CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
+  #       with:
+  #         configuration: ${{ env.configuration }}
+  #     - name: export
+  #       run: |
+  #         version=$(conan inspect --raw version .)
+  #         reference="xrpl/${version}@local/test"
+  #         conan remove -f ${reference} || true
+  #         conan export . local/test
+  #         echo "reference=${reference}" >> "${GITHUB_ENV}"
+  #     - name: build
+  #       run: |
+  #         cd tests/conan
+  #         mkdir ${build_dir}
+  #         cd ${build_dir}
+  #         conan install .. --output-folder . \
+  #           --require-override ${reference} --build missing
+  #         cmake .. \
+  #           -DCMAKE_TOOLCHAIN_FILE:FILEPATH=./build/${configuration}/generators/conan_toolchain.cmake \
+  #           -DCMAKE_BUILD_TYPE=${configuration}
+  #         cmake --build .
+  #         ./example | grep '^[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+'
 
   # NOTE we are not using dependencies built above because it lags with
   # compiler versions. Instrumentation requires clang version 16 or
